// Generated by gencpp from file beginner_tutorials/Sim.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_SIM_H
#define BEGINNER_TUTORIALS_MESSAGE_SIM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace beginner_tutorials
{
template <class ContainerAllocator>
struct Sim_
{
  typedef Sim_<ContainerAllocator> Type;

  Sim_()
    : header()
    , id(0)
    , prob(0.0)
    , x(0.0)
    , y(0.0)
    , gl(false)
    , rb(false)
    , lb(false)
    , bb(false)
    , time(0.0)  {
    }
  Sim_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)
    , prob(0.0)
    , x(0.0)
    , y(0.0)
    , gl(false)
    , rb(false)
    , lb(false)
    , bb(false)
    , time(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _id_type;
  _id_type id;

   typedef double _prob_type;
  _prob_type prob;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef uint8_t _gl_type;
  _gl_type gl;

   typedef uint8_t _rb_type;
  _rb_type rb;

   typedef uint8_t _lb_type;
  _lb_type lb;

   typedef uint8_t _bb_type;
  _bb_type bb;

   typedef double _time_type;
  _time_type time;




  typedef boost::shared_ptr< ::beginner_tutorials::Sim_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::Sim_<ContainerAllocator> const> ConstPtr;

}; // struct Sim_

typedef ::beginner_tutorials::Sim_<std::allocator<void> > Sim;

typedef boost::shared_ptr< ::beginner_tutorials::Sim > SimPtr;
typedef boost::shared_ptr< ::beginner_tutorials::Sim const> SimConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::Sim_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::Sim_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'beginner_tutorials': ['/home/redbird/catkin_ws/src/beginner_tutorials/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::Sim_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::Sim_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::Sim_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::Sim_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::Sim_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::Sim_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::Sim_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bcaa2b3604268669fe424b85bea488e8";
  }

  static const char* value(const ::beginner_tutorials::Sim_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbcaa2b3604268669ULL;
  static const uint64_t static_value2 = 0xfe424b85bea488e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::Sim_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/Sim";
  }

  static const char* value(const ::beginner_tutorials::Sim_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::Sim_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int16 id 	#ROOmba's id\n\
\n\
float64 prob #Roomba's probability\n\
\n\
float64 x 	#Roomba's origin x\n\
float64 y 	#Roomba's origin y\n\
\n\
bool gl\n\
bool rb\n\
bool lb\n\
bool bb\n\
#Above variables are for boundary detection\n\
\n\
float64 time\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::beginner_tutorials::Sim_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::Sim_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.prob);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.gl);
      stream.next(m.rb);
      stream.next(m.lb);
      stream.next(m.bb);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Sim_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::Sim_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::Sim_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.id);
    s << indent << "prob: ";
    Printer<double>::stream(s, indent + "  ", v.prob);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "gl: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gl);
    s << indent << "rb: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rb);
    s << indent << "lb: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.lb);
    s << indent << "bb: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bb);
    s << indent << "time: ";
    Printer<double>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_SIM_H
