# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from beginner_tutorials/Sim.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class Sim(genpy.Message):
  _md5sum = "bcaa2b3604268669fe424b85bea488e8"
  _type = "beginner_tutorials/Sim"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
int16 id 	#ROOmba's id

float64 prob #Roomba's probability

float64 x 	#Roomba's origin x
float64 y 	#Roomba's origin y

bool gl
bool rb
bool lb
bool bb
#Above variables are for boundary detection

float64 time
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  __slots__ = ['header','id','prob','x','y','gl','rb','lb','bb','time']
  _slot_types = ['std_msgs/Header','int16','float64','float64','float64','bool','bool','bool','bool','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,id,prob,x,y,gl,rb,lb,bb,time

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Sim, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.id is None:
        self.id = 0
      if self.prob is None:
        self.prob = 0.
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.gl is None:
        self.gl = False
      if self.rb is None:
        self.rb = False
      if self.lb is None:
        self.lb = False
      if self.bb is None:
        self.bb = False
      if self.time is None:
        self.time = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.id = 0
      self.prob = 0.
      self.x = 0.
      self.y = 0.
      self.gl = False
      self.rb = False
      self.lb = False
      self.bb = False
      self.time = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_h3d4Bd().pack(_x.id, _x.prob, _x.x, _x.y, _x.gl, _x.rb, _x.lb, _x.bb, _x.time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 38
      (_x.id, _x.prob, _x.x, _x.y, _x.gl, _x.rb, _x.lb, _x.bb, _x.time,) = _get_struct_h3d4Bd().unpack(str[start:end])
      self.gl = bool(self.gl)
      self.rb = bool(self.rb)
      self.lb = bool(self.lb)
      self.bb = bool(self.bb)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_h3d4Bd().pack(_x.id, _x.prob, _x.x, _x.y, _x.gl, _x.rb, _x.lb, _x.bb, _x.time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 38
      (_x.id, _x.prob, _x.x, _x.y, _x.gl, _x.rb, _x.lb, _x.bb, _x.time,) = _get_struct_h3d4Bd().unpack(str[start:end])
      self.gl = bool(self.gl)
      self.rb = bool(self.rb)
      self.lb = bool(self.lb)
      self.bb = bool(self.bb)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_h3d4Bd = None
def _get_struct_h3d4Bd():
    global _struct_h3d4Bd
    if _struct_h3d4Bd is None:
        _struct_h3d4Bd = struct.Struct("<h3d4Bd")
    return _struct_h3d4Bd
